#!/usr/bin/env node

/**
 * Sync version from logs/DEVLOG.md to src/version.ts
 * 
 * This script reads the version from the DEVLOG.md "Current Context" section
 * and updates src/version.ts to match.
 * 
 * Run manually: node scripts/sync-version.js
 * Or automatically via: npm run build (pre-build hook)
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

const DEVLOG_PATH = join(rootDir, 'logs/DEVLOG.md');
const VERSION_PATH = join(rootDir, 'src/version.ts');

function extractVersionFromDevlog() {
  try {
    const content = readFileSync(DEVLOG_PATH, 'utf-8');
    
    // Look for **Version:** v0.1.0-dev pattern in Current Context section
    const versionMatch = content.match(/\*\*Version:\*\*\s*v?([\d]+\.[\d]+\.[\d]+(?:-[\w]+)?)/);
    
    if (versionMatch) {
      return versionMatch[1];
    }
    
    console.warn('Warning: Could not find version in DEVLOG.md, using fallback');
    return '0.0.0-unknown';
  } catch (error) {
    console.error('Error reading DEVLOG.md:', error.message);
    return '0.0.0-unknown';
  }
}

function generateVersionFile(version) {
  const content = `/**
 * Application version configuration
 * 
 * AUTO-GENERATED - Do not edit manually!
 * This file is generated by scripts/sync-version.js from logs/DEVLOG.md
 * 
 * To update the version:
 * 1. Edit logs/DEVLOG.md "Current Context" section
 * 2. Run: npm run sync-version (or it runs automatically on build)
 */

export const APP_VERSION = "${version}";
export const APP_NAME = "Brand Guidelines Manager";
export const COMPANY_NAME = "Cake Websites";
`;

  writeFileSync(VERSION_PATH, content, 'utf-8');
  console.log(`✓ Version synced: v${version}`);
}

const version = extractVersionFromDevlog();
generateVersionFile(version);

