/**
 * Application version configuration
 * 
 * AUTO-GENERATED - Do not edit manually!
 * This file is generated by scripts/sync-version.js from logs/DEVLOG.md
 * 
 * To update the version:
 * 1. Edit logs/DEVLOG.md "Current Context" section
 * 2. Run: npm run sync-version (or it runs automatically on build)
 */

export const APP_VERSION = "0.1.0-dev";
export const APP_NAME = "Brand Guidelines Manager";
export const COMPANY_NAME = "Cake Websites";
